#!/usr/bin/env python3
"""Add missing practical-exam vocabulary (batch 3) — traffic faults, technik, exam protocol."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VOCAB_PATH = ROOT / "FahrPrufungDE" / "Resources" / "vocabulary.json"

NEW_TERMS: list[dict] = [
    # --- traffic: road users ---
    {
        "id": "motorradfahrer",
        "de": "Der Motorradfahrer",
        "article": "der",
        "de_base": "Motorradfahrer",
        "ru": "Мотоциклист",
        "en": "Motorcyclist",
        "uk": "Мотоцикліст",
        "fr": "Motocycliste",
        "tr": "Motosiklet sürücüsü",
        "category": "traffic",
        "tags": ["core"],
    },
    {
        "id": "lkw",
        "de": "Der Lkw (Lastkraftwagen)",
        "article": "der",
        "de_base": "Lkw",
        "ru": "Грузовой автомобиль (Lkw)",
        "en": "Heavy goods vehicle (lorry / truck)",
        "uk": "Вантажний автомобіль (Lkw)",
        "fr": "Poids lourd (camion)",
        "tr": "Kamyon (ağır vasıta)",
        "category": "traffic",
        "tags": ["core"],
    },
    {
        "id": "strassenbahn",
        "de": "Die Straßenbahn",
        "article": "die",
        "de_base": "Straßenbahn",
        "ru": "Трамвай",
        "en": "Tram (streetcar)",
        "uk": "Трамвай",
        "fr": "Tramway",
        "tr": "Tramvay",
        "category": "traffic",
        "tags": ["core"],
    },
    # --- traffic: signs / prohibitions ---
    {
        "id": "verkehrsverbot",
        "de": "Das Verkehrsverbot",
        "article": "das",
        "de_base": "Verkehrsverbot",
        "ru": "Запрет движения транспортных средств",
        "en": "General traffic prohibition",
        "uk": "Заборона руху транспортних засобів",
        "fr": "Interdiction de circuler",
        "tr": "Trafik yasağı",
        "category": "traffic",
        "tags": [],
    },
    {
        "id": "verbot_der_einfahrt",
        "de": "Das Verbot der Einfahrt",
        "article": "das",
        "de_base": "Verbot der Einfahrt",
        "ru": "Запрет въезда",
        "en": "No entry",
        "uk": "Заборона в'їзду",
        "fr": "Sens interdit / entrée interdite",
        "tr": "Giriş yasağı",
        "category": "traffic",
        "tags": ["core"],
    },
    {
        "id": "ueberholverbot",
        "de": "Das Überholverbot",
        "article": "das",
        "de_base": "Überholverbot",
        "ru": "Запрет обгона",
        "en": "No overtaking",
        "uk": "Заборона обгону",
        "fr": "Interdiction de dépasser",
        "tr": "Sollama yasağı",
        "category": "traffic",
        "tags": ["core"],
    },
    {
        "id": "rechtsabbiegepfeil",
        "de": "Der Rechtsabbiegepfeil (Linksabbiegepfeil)",
        "article": "der",
        "de_base": "Rechtsabbiegepfeil",
        "ru": "Указатель обязательного поворота направо (налево)",
        "en": "Mandatory turn arrow (right / left)",
        "uk": "Вказівник обов'язкового повороту праворуч (ліворуч)",
        "fr": "Flèche de direction obligatoire (droite / gauche)",
        "tr": "Zorunlu dönüş oku (sağ / sol)",
        "category": "traffic",
        "tags": [],
    },
    {
        "id": "ampel_rot_gelb_gruen",
        "de": "Ampel rot (gelb, grün)",
        "article": None,
        "de_base": "Ampel rot (gelb, grün)",
        "ru": "Светофор: красный (жёлтый, зелёный) сигнал",
        "en": "Traffic lights: red (amber, green)",
        "uk": "Світлофор: червоний (жовтий, зелений) сигнал",
        "fr": "Feu tricolore : rouge (orange, vert)",
        "tr": "Trafik lambası: kırmızı (sarı, yeşil)",
        "category": "traffic",
        "tags": ["core"],
    },
    # --- exam: evaluation faults ---
    {
        "id": "fehler_zu_wenig_abstand",
        "de": "Zu wenig Abstand beim Vorbeifahren (Überholen) von …",
        "article": None,
        "de_base": "Zu wenig Abstand beim Vorbeifahren (Überholen) von …",
        "ru": "Недостаточный боковой интервал при обгоне (опережении) …",
        "en": "Insufficient lateral clearance when overtaking …",
        "uk": "Недостатній боковий інтервал під час обгону (випередження) …",
        "fr": "Distance latérale insuffisante lors du dépassement de …",
        "tr": "Sollama (geçme) sırasında yetersiz yan mesafe: …",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "fehler_vorfahrt_nicht_beachtet",
        "de": "Vorfahrt (Vorrang) nicht beachtet bei …",
        "article": None,
        "de_base": "Vorfahrt (Vorrang) nicht beachtet bei …",
        "ru": "Не предоставлено преимущество в движении при …",
        "en": "Failure to yield right of way when …",
        "uk": "Не надано перевагу в русі при …",
        "fr": "Priorité non respectée lors de …",
        "tr": "Geçiş üstünlüğüne uyulmadı: …",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "vorrang_fussgaenger",
        "de": "Der Vorrang der Fußgänger",
        "article": "der",
        "de_base": "Vorrang der Fußgänger",
        "ru": "Преимущество (приоритет) пешеходов",
        "en": "Pedestrian right of way",
        "uk": "Перевага (пріоритет) пішоходів",
        "fr": "Priorité des piétons",
        "tr": "Yayaların geçiş üstünlüğü",
        "category": "traffic",
        "tags": ["core"],
    },
    {
        "id": "fehler_verkehrszeichen",
        "de": "Nichtbeachten von Verkehrszeichen",
        "article": None,
        "de_base": "Nichtbeachten von Verkehrszeichen",
        "ru": "Несоблюдение дорожных знаков",
        "en": "Failure to observe traffic signs",
        "uk": "Недотримання дорожніх знаків",
        "fr": "Non-respect des panneaux de signalisation",
        "tr": "Trafik işaretlerine uyulmaması",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "fehler_bus_vorbeifahren",
        "de": "Zu schnell an Bus vorbeigefahren",
        "article": None,
        "de_base": "Zu schnell an Bus vorbeigefahren",
        "ru": "Обгон автобуса с превышением допустимой скорости",
        "en": "Overtook a bus at excessive speed",
        "uk": "Обгін автобуса з перевищенням допустимої швидкості",
        "fr": "Dépassement d'un bus à vitesse excessive",
        "tr": "Otobüsü izin verilenden yüksek hızla sollama",
        "category": "exam",
        "tags": [],
    },
    {
        "id": "erhebliches_fehlverhalten",
        "de": "Erhebliches Fehlverhalten",
        "article": None,
        "de_base": "Erhebliches Fehlverhalten",
        "ru": "Существенное нарушение (основание для неудовлетворительной оценки)",
        "en": "Serious fault (substantial misconduct)",
        "uk": "Істотне порушення (підстава для незадовільної оцінки)",
        "fr": "Faute grave (manquement important)",
        "tr": "Ciddi kusur (önemli ihlal)",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "haeufung_fehler",
        "de": "Häufung oder Wiederholung von Fehlern",
        "article": None,
        "de_base": "Häufung oder Wiederholung von Fehlern",
        "ru": "Многократные или повторяющиеся ошибки",
        "en": "Accumulation or repetition of faults",
        "uk": "Множинні або повторювані помилки",
        "fr": "Accumulation ou répétition de fautes",
        "tr": "Hataların birikimi veya tekrarı",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "grundfahraufgabe_wiederholt_fehlerhaft",
        "de": "Grundfahraufgabe wiederholt fehlerhaft",
        "article": None,
        "de_base": "Grundfahraufgabe wiederholt fehlerhaft",
        "ru": "Основное маневровое задание повторно выполнено с нарушениями",
        "en": "Basic manoeuvre task repeatedly performed incorrectly",
        "uk": "Основне маневрове завдання повторно виконано з порушеннями",
        "fr": "Manœuvre de base à nouveau exécutée de manière incorrecte",
        "tr": "Temel sürüş manevrası tekrar hatalı yapıldı",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "gefaehrdung",
        "de": "Die Gefährdung",
        "article": "die",
        "de_base": "Gefährdung",
        "ru": "Создание опасности для участников дорожного движения",
        "en": "Endangering other road users",
        "uk": "Створення небезпеки для учасників дорожнього руху",
        "fr": "Mise en danger d'autres usagers de la route",
        "tr": "Diğer yol kullanıcılarını tehlikeye atma",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "fehler_zu_langsam_schnell",
        "de": "Zu langsam / schnell",
        "article": None,
        "de_base": "Zu langsam / schnell",
        "ru": "Слишком медленно / быстро",
        "en": "Too slow / too fast",
        "uk": "Занадто повільно / швидко",
        "fr": "Trop lent / trop rapide",
        "tr": "Çok yavaş / çok hızlı",
        "category": "exam",
        "tags": [],
    },
    {
        "id": "unsicher_fahren",
        "de": "Unsicher",
        "article": None,
        "de_base": "Unsicher",
        "ru": "Неуверенное вождение",
        "en": "Uncertain / insecure driving",
        "uk": "Невпевнене водіння",
        "fr": "Conduite hésitante / peu sûre",
        "tr": "Güvensiz / kararsız sürüş",
        "category": "exam",
        "tags": [],
    },
    {
        "id": "fehlende_verkehrsbeobachtung",
        "de": "Fehlende Verkehrsbeobachtung bei …",
        "article": None,
        "de_base": "Fehlende Verkehrsbeobachtung bei …",
        "ru": "Отсутствие наблюдения за дорожной обстановкой при …",
        "en": "Failure to observe traffic when …",
        "uk": "Відсутність спостереження за дорожньою обстановкою при …",
        "fr": "Absence d'observation de la circulation lors de …",
        "tr": "Trafik gözlemi yapılmadı: …",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "fehlende_spiegelbeobachtung",
        "de": "Fehlende oder ungenügende Spiegelbeobachtung",
        "article": None,
        "de_base": "Fehlende oder ungenügende Spiegelbeobachtung",
        "ru": "Отсутствие или недостаточный контроль в зеркалах",
        "en": "Missing or inadequate mirror checks",
        "uk": "Відсутність або недостатній контроль у дзеркалах",
        "fr": "Contrôle des rétroviseurs absent ou insuffisant",
        "tr": "Ayna kontrolü yapılmadı veya yetersiz",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "fehlendes_vorausschauendes_fahren",
        "de": "Fehlendes vorausschauendes Fahren",
        "article": None,
        "de_base": "Fehlendes vorausschauendes Fahren",
        "ru": "Отсутствие упреждающего вождения",
        "en": "Lack of anticipatory driving",
        "uk": "Відсутність упреждаючого водіння",
        "fr": "Absence de conduite anticipée",
        "tr": "Öngörülü sürüş eksikliği",
        "category": "exam",
        "tags": ["core"],
    },
    # --- exam: protocol ---
    {
        "id": "fahrtechnischer_abschluss",
        "de": "Der Fahrtechnische Abschluss",
        "article": "der",
        "de_base": "Fahrtechnischer Abschluss",
        "ru": "Аттестация практических навыков вождения",
        "en": "Practical driving skills assessment",
        "uk": "Атестація практичних навичок водіння",
        "fr": "Épreuve pratique de conduite (bilan technique)",
        "tr": "Pratik sürüş becerileri değerlendirmesi",
        "category": "exam",
        "tags": [],
    },
    {
        "id": "abschluss_der_pruefung",
        "de": "Der Abschluss der Prüfung",
        "article": "der",
        "de_base": "Abschluss der Prüfung",
        "ru": "Завершение экзамена",
        "en": "Conclusion of the examination",
        "uk": "Завершення іспиту",
        "fr": "Clôture de l'examen",
        "tr": "Sınavın sona ermesi",
        "category": "exam",
        "tags": [],
    },
    {
        "id": "pruefung_nicht_bestanden",
        "de": "Prüfung [nicht] bestanden",
        "article": None,
        "de_base": "Prüfung [nicht] bestanden",
        "ru": "Экзамен [не] сдан",
        "en": "Examination [not] passed",
        "uk": "Іспит [не] складено",
        "fr": "Examen [non] réussi",
        "tr": "Sınav [geçilemedi / geçildi]",
        "category": "exam",
        "tags": ["core"],
    },
    {
        "id": "sicherung_gegen",
        "de": "Sicherung (Sichern) gegen …",
        "article": None,
        "de_base": "Sicherung (Sichern) gegen …",
        "ru": "Предохранение (закрепление) от …",
        "en": "Securing (safeguarding) against …",
        "uk": "Запобігання (закріплення) від …",
        "fr": "Sécurisation contre …",
        "tr": "… karşı güvence (sabitleme)",
        "category": "safety",
        "tags": [],
    },
    {
        "id": "unbefugte_benutzung",
        "de": "Die unbefugte Benutzung",
        "article": "die",
        "de_base": "unbefugte Benutzung",
        "ru": "Несанкционированное использование транспортного средства",
        "en": "Unauthorised use (of the vehicle)",
        "uk": "Несанкціоноване використання транспортного засобу",
        "fr": "Utilisation non autorisée (du véhicule)",
        "tr": "İzinsiz kullanım",
        "category": "safety",
        "tags": [],
    },
    {
        "id": "umschau_beim_aussteigen",
        "de": "Umschau (Umsicht) beim Aussteigen",
        "article": None,
        "de_base": "Umschau (Umsicht) beim Aussteigen",
        "ru": "Осмотр (оглядка) при выходе из транспортного средства",
        "en": "Look around (check surroundings) when exiting the vehicle",
        "uk": "Огляд (оглядання) при виході з транспортного засобу",
        "fr": "Contrôle visuel en sortant du véhicule",
        "tr": "Araçtan inerken etrafı kontrol etme",
        "category": "safety",
        "tags": ["core"],
    },
    {
        "id": "wegrollen",
        "de": "Das Wegrollen",
        "article": "das",
        "de_base": "Wegrollen",
        "ru": "Самопроизвольное движение (откат) транспортного средства",
        "en": "Unintended rolling of the vehicle",
        "uk": "Самовільний рух (відкат) транспортного засобу",
        "fr": "Roulage involontaire du véhicule",
        "tr": "Aracın istenmeden hareket etmesi (yuvarlanma)",
        "category": "safety",
        "tags": [],
    },
    # --- technik / safety check ---
    {
        "id": "sicherheitskontrolle",
        "de": "Die Sicherheitskontrolle",
        "article": "die",
        "de_base": "Sicherheitskontrolle",
        "ru": "Проверка технического состояния и безопасности (Sicherheitskontrolle)",
        "en": "Pre-drive safety inspection",
        "uk": "Перевірка технічного стану та безпеки (Sicherheitskontrolle)",
        "fr": "Contrôle de sécurité du véhicule",
        "tr": "Güvenlik kontrolü (araç kontrolü)",
        "category": "technik",
        "tags": ["core", "exam"],
        "exam_phrase_de": "Bitte führen Sie die Sicherheitskontrolle durch.",
    },
    {
        "id": "fluessigkeitsstaende_pruefen",
        "de": "Flüssigkeitsstände prüfen",
        "article": None,
        "de_base": "Flüssigkeitsstände prüfen",
        "ru": "Проверить уровни эксплуатационных жидкостей",
        "en": "Check fluid levels",
        "uk": "Перевірити рівні експлуатаційних рідин",
        "fr": "Contrôler les niveaux de liquides",
        "tr": "Sıvı seviyelerini kontrol etmek",
        "category": "fluids",
        "tags": ["core", "exam"],
    },
    {
        "id": "reifen_kontrollieren",
        "de": "Reifen kontrollieren",
        "article": None,
        "de_base": "Reifen kontrollieren",
        "ru": "Проверить состояние шин",
        "en": "Check the tyres",
        "uk": "Перевірити стан шин",
        "fr": "Contrôler les pneus",
        "tr": "Lastikleri kontrol etmek",
        "category": "car",
        "tags": ["core", "exam"],
    },
    {
        "id": "raeder_kontrollieren",
        "de": "Räder kontrollieren",
        "article": None,
        "de_base": "Räder kontrollieren",
        "ru": "Проверить колёса",
        "en": "Check the wheels",
        "uk": "Перевірити колеса",
        "fr": "Contrôler les roues",
        "tr": "Tekerlekleri kontrol etmek",
        "category": "car",
        "tags": [],
    },
    {
        "id": "beschaedigung",
        "de": "Die Beschädigung",
        "article": "die",
        "de_base": "Beschädigung",
        "ru": "Повреждение (дефект)",
        "en": "Damage (defect)",
        "uk": "Пошкодження (дефект)",
        "fr": "Dommage (défaut)",
        "tr": "Hasar (arıza)",
        "category": "technik",
        "tags": [],
    },
    {
        "id": "beschaedigungen",
        "de": "Die Beschädigungen",
        "article": "die",
        "de_base": "Beschädigungen",
        "ru": "Повреждения",
        "en": "Damage (defects)",
        "uk": "Пошкодження",
        "fr": "Dommages",
        "tr": "Hasarlar",
        "category": "technik",
        "tags": [],
    },
    {
        "id": "vorhanden_sein",
        "de": "Vorhanden sein",
        "article": None,
        "de_base": "Vorhanden sein",
        "ru": "Наличие (присутствие) в исправном состоянии",
        "en": "To be present and intact",
        "uk": "Наявність (присутність) у справному стані",
        "fr": "Être présent et en bon état",
        "tr": "Mevcut ve sağlam olmak",
        "category": "technik",
        "tags": [],
    },
    {
        "id": "funktion_pruefen",
        "de": "Funktion von … prüfen",
        "article": None,
        "de_base": "Funktion von … prüfen",
        "ru": "Проверить работоспособность …",
        "en": "Check the function of …",
        "uk": "Перевірити працездатність …",
        "fr": "Vérifier le fonctionnement de …",
        "tr": "… işlevini kontrol etmek",
        "category": "technik",
        "tags": ["core", "exam"],
    },
    {
        "id": "ein_ausschalten_von",
        "de": "Ein- und Ausschalten von …",
        "article": None,
        "de_base": "Ein- und Ausschalten von …",
        "ru": "Включение и выключение …",
        "en": "Switching on and off …",
        "uk": "Увімкнення та вимкнення …",
        "fr": "Mise en marche et arrêt de …",
        "tr": "… açma ve kapatma",
        "category": "technik",
        "tags": ["exam"],
    },
    {
        "id": "zeigen_von",
        "de": "Zeigen von …",
        "article": None,
        "de_base": "Zeigen von …",
        "ru": "Показать … (продемонстрировать)",
        "en": "Show / demonstrate …",
        "uk": "Показати … (продемонструвати)",
        "fr": "Montrer / faire la démonstration de …",
        "tr": "… göstermek",
        "category": "technik",
        "tags": ["exam"],
    },
    {
        "id": "kontrollleuchten_benennen",
        "de": "Kontrollleuchten benennen",
        "article": None,
        "de_base": "Kontrollleuchten benennen",
        "ru": "Назвать контрольные индикаторы (на панели приборов)",
        "en": "Name the warning / indicator lights",
        "uk": "Назвати контрольні індикатори (на панелі приладів)",
        "fr": "Nommer les témoins lumineux",
        "tr": "Uyarı / kontrol lambalarını adlandırmak",
        "category": "technik",
        "tags": ["exam"],
    },
    # --- car: controls & terms ---
    {
        "id": "fahrzeugbegriffe",
        "de": "Die Fahrzeugbegriffe",
        "article": "die",
        "de_base": "Fahrzeugbegriffe",
        "ru": "Терминология устройства автомобиля",
        "en": "Vehicle terminology",
        "uk": "Термінологія пристрою автомобіля",
        "fr": "Terminologie du véhicule",
        "tr": "Araç terimleri",
        "category": "car",
        "tags": [],
    },
    {
        "id": "bremse",
        "de": "Die Bremse",
        "article": "die",
        "de_base": "Bremse",
        "ru": "Тормоз (тормозная система)",
        "en": "Brake (braking system)",
        "uk": "Гальмо (гальмівна система)",
        "fr": "Frein (système de freinage)",
        "tr": "Fren (fren sistemi)",
        "category": "brakes",
        "tags": [],
    },
    {
        "id": "fussbremse",
        "de": "Die Fußbremse",
        "article": "die",
        "de_base": "Fußbremse",
        "ru": "Ножной (рабочий) тормоз",
        "en": "Foot brake (service brake)",
        "uk": "Ножне (робоче) гальмо",
        "fr": "Frein à pied (frein de service)",
        "tr": "Ayak freni (hizmet freni)",
        "category": "brakes",
        "tags": [],
    },
    {
        "id": "schalthebel",
        "de": "Der Schalthebel",
        "article": "der",
        "de_base": "Schalthebel",
        "ru": "Рычаг переключения передач",
        "en": "Gear lever",
        "uk": "Важіль перемикання передач",
        "fr": "Levier de vitesses",
        "tr": "Vites kolu",
        "category": "car",
        "tags": ["core"],
    },
    {
        "id": "zweiter_gang",
        "de": "Der zweite Gang",
        "article": "der",
        "de_base": "zweiter Gang",
        "ru": "Вторая передача",
        "en": "Second gear",
        "uk": "Друга передача",
        "fr": "Deuxième vitesse",
        "tr": "İkinci vites",
        "category": "car",
        "tags": [],
    },
    {
        "id": "dritter_gang",
        "de": "Der dritte Gang",
        "article": "der",
        "de_base": "dritter Gang",
        "ru": "Третья передача",
        "en": "Third gear",
        "uk": "Третя передача",
        "fr": "Troisième vitesse",
        "tr": "Üçüncü vites",
        "category": "car",
        "tags": [],
    },
    {
        "id": "vierter_gang",
        "de": "Der vierte Gang",
        "article": "der",
        "de_base": "vierter Gang",
        "ru": "Четвёртая передача",
        "en": "Fourth gear",
        "uk": "Четверта передача",
        "fr": "Quatrième vitesse",
        "tr": "Dördüncü vites",
        "category": "car",
        "tags": [],
    },
    {
        "id": "fuenfter_gang",
        "de": "Der fünfte Gang",
        "article": "der",
        "de_base": "fünfter Gang",
        "ru": "Пятая передача",
        "en": "Fifth gear",
        "uk": "П'ята передача",
        "fr": "Cinquième vitesse",
        "tr": "Beşinci vites",
        "category": "car",
        "tags": [],
    },
    {
        "id": "lichtschalter",
        "de": "Der Lichtschalter",
        "article": "der",
        "de_base": "Lichtschalter",
        "ru": "Переключатель света",
        "en": "Light switch",
        "uk": "Перемикач світла",
        "fr": "Commutateur d'éclairage",
        "tr": "Işık anahtarı",
        "category": "car",
        "tags": [],
    },
    {
        "id": "heizung",
        "de": "Die Heizung",
        "article": "die",
        "de_base": "Heizung",
        "ru": "Отопление (система обогрева салона)",
        "en": "Heating (cabin heater)",
        "uk": "Опалення (система обігріву салону)",
        "fr": "Chauffage (habitacle)",
        "tr": "Isıtma (kabin ısıtıcısı)",
        "category": "car",
        "tags": [],
    },
    {
        "id": "geblaese",
        "de": "Das Gebläse",
        "article": "das",
        "de_base": "Gebläse",
        "ru": "Вентилятор-нагнетатель (обдува)",
        "en": "Blower (ventilation fan)",
        "uk": "Вентилятор-нагнітач (обдуву)",
        "fr": "Soufflerie (ventilation)",
        "tr": "Üfleyici (havalandırma fanı)",
        "category": "car",
        "tags": [],
    },
    {
        "id": "fenster_oeffnen_schliessen",
        "de": "Fenster öffnen (schließen)",
        "article": None,
        "de_base": "Fenster öffnen (schließen)",
        "ru": "Открыть (закрыть) окно",
        "en": "Open (close) the window",
        "uk": "Відкрити (закрити) вікно",
        "fr": "Ouvrir (fermer) la vitre",
        "tr": "Camı açmak (kapatmak)",
        "category": "car",
        "tags": [],
    },
    {
        "id": "spiegel_einstellen",
        "de": "Spiegel [einstellen]",
        "article": None,
        "de_base": "Spiegel einstellen",
        "ru": "Настроить зеркало",
        "en": "Adjust the mirror",
        "uk": "Налаштувати дзеркало",
        "fr": "Régler le rétroviseur",
        "tr": "Aynayı ayarlamak",
        "category": "car",
        "tags": [],
    },
    {
        "id": "aussenspiegel_einstellen",
        "de": "Außenspiegel [einstellen]",
        "article": None,
        "de_base": "Außenspiegel einstellen",
        "ru": "Настроить наружное зеркало",
        "en": "Adjust the exterior mirror",
        "uk": "Налаштувати зовнішнє дзеркало",
        "fr": "Régler le rétroviseur extérieur",
        "tr": "Dış aynayı ayarlamak",
        "category": "car",
        "tags": [],
    },
    {
        "id": "heckscheibenheizung_einschalten",
        "de": "Heckscheibenheizung einschalten",
        "article": None,
        "de_base": "Heckscheibenheizung einschalten",
        "ru": "Включить обогрев заднего стекла",
        "en": "Switch on the rear window defroster",
        "uk": "Увімкнути обігрів заднього скла",
        "fr": "Activer le dégivrage de la lunette arrière",
        "tr": "Arka cam buz çözücüyü açmak",
        "category": "car",
        "tags": [],
    },
    {
        "id": "lenkung",
        "de": "Die Lenkung",
        "article": "die",
        "de_base": "Lenkung",
        "ru": "Рулевое управление",
        "en": "Steering system",
        "uk": "Рульове керування",
        "fr": "Direction (système de direction)",
        "tr": "Direksiyon sistemi",
        "category": "car",
        "tags": [],
    },
    {
        "id": "lenkschloss_entriegeln",
        "de": "Lenkschloss entriegeln",
        "article": None,
        "de_base": "Lenkschloss entriegeln",
        "ru": "Разблокировать замок рулевого управления",
        "en": "Unlock the steering lock",
        "uk": "Розблокувати замок рульового керування",
        "fr": "Déverrouiller le verrou de direction",
        "tr": "Direksiyon kilidini açmak",
        "category": "car",
        "tags": ["exam"],
    },
    # --- lights ---
    {
        "id": "schlussleuchte_kennzeichen",
        "de": "Schlussleuchten mit Kennzeichenbeleuchtung",
        "article": None,
        "de_base": "Schlussleuchten mit Kennzeichenbeleuchtung",
        "ru": "Задние габаритные огни с подсветкой номерного знака",
        "en": "Rear lights with number plate illumination",
        "uk": "Задні габаритні вогні з підсвіткою номерного знака",
        "fr": "Feux arrière avec éclairage de plaque",
        "tr": "Plaka aydınlatmalı arka lambalar",
        "category": "lights",
        "tags": ["core", "exam"],
    },
    {
        "id": "bremsleuchte",
        "de": "Die Bremsleuchte(n)",
        "article": "die",
        "de_base": "Bremsleuchte",
        "ru": "Фонарь (фонари) сигнала торможения",
        "en": "Brake light(s)",
        "uk": "Ліхтар (ліхтарі) сигналу гальмування",
        "fr": "Feu(x) stop",
        "tr": "Fren lambası / fren lambaları",
        "category": "lights",
        "tags": ["core", "exam"],
    },
    {
        "id": "rueckstrahler",
        "de": "Der Rückstrahler",
        "article": "der",
        "de_base": "Rückstrahler",
        "ru": "Световозвращатель (катафот)",
        "en": "Rear reflector",
        "uk": "Світловідбивач (катафот)",
        "fr": "Catadioptre arrière",
        "tr": "Arka reflektör",
        "category": "lights",
        "tags": [],
    },
    # --- examiner direction / maneuver headers ---
    {
        "id": "phrase_angabe_pruefungsfahrt",
        "de": "Angabe während der Prüfungsfahrt",
        "article": None,
        "de_base": "Angabe während der Prüfungsfahrt",
        "ru": "Указания во время практического экзамена",
        "en": "Instructions during the practical test drive",
        "uk": "Вказівки під час практичного іспиту",
        "fr": "Consignes pendant l'épreuve pratique",
        "tr": "Uygulamalı sınav sırasında talimatlar",
        "category": "phrases",
        "tags": ["examiner", "direction"],
        "exam_phrase_de": "Angabe während der Prüfungsfahrt",
    },
    {
        "id": "phrase_links",
        "de": "Links.",
        "article": None,
        "de_base": "Links",
        "ru": "Налево.",
        "en": "Left.",
        "uk": "Ліворуч.",
        "fr": "À gauche.",
        "tr": "Sola.",
        "category": "phrases",
        "tags": ["examiner", "direction"],
        "exam_phrase_de": "Links.",
    },
    {
        "id": "phrase_rechts",
        "de": "Rechts.",
        "article": None,
        "de_base": "Rechts",
        "ru": "Направо.",
        "en": "Right.",
        "uk": "Праворуч.",
        "fr": "À droite.",
        "tr": "Sağa.",
        "category": "phrases",
        "tags": ["examiner", "direction"],
        "exam_phrase_de": "Rechts.",
    },
    {
        "id": "manoeverangaben",
        "de": "Die Manöverangaben",
        "article": "die",
        "de_base": "Manöverangaben",
        "ru": "Указания для выполнения манёвров",
        "en": "Manoeuvre instructions",
        "uk": "Вказівки для виконання маневрів",
        "fr": "Consignes de manœuvre",
        "tr": "Manevra talimatları",
        "category": "maneuvers",
        "tags": ["core"],
    },
    {
        "id": "phrase_strasse_rechts_nummer",
        "de": "Erste (zweite, dritte, vierte) Straße rechts",
        "article": None,
        "de_base": "Erste (zweite, dritte, vierte) Straße rechts",
        "ru": "Первая (вторая, третья, четвёртая) улица направо",
        "en": "First (second, third, fourth) street on the right",
        "uk": "Перша (друга, третя, четверта) вулиця праворуч",
        "fr": "Première (deuxième, troisième, quatrième) rue à droite",
        "tr": "Sağdaki birinci (ikinci, üçüncü, dördüncü) sokak",
        "category": "phrases",
        "tags": ["examiner", "direction"],
        "exam_phrase_de": "Nehmen Sie die erste Straße rechts.",
    },
    {
        "id": "phrase_in_richtung_fahren",
        "de": "In Richtung … fahren",
        "article": None,
        "de_base": "In Richtung … fahren",
        "ru": "Двигаться в направлении …",
        "en": "Drive in the direction of …",
        "uk": "Рухатися в напрямку …",
        "fr": "Rouler en direction de …",
        "tr": "… yönünde gitmek",
        "category": "phrases",
        "tags": ["examiner", "direction"],
        "exam_phrase_de": "Fahren Sie in Richtung Stadtzentrum.",
    },
]


def normalize_de(text: str) -> str:
    text = text.lower().strip().rstrip(".")
    text = re.sub(r"\s+", " ", text)
    return text


def main() -> None:
    with open(VOCAB_PATH, encoding="utf-8") as f:
        data = json.load(f)

    existing_ids = {t["id"] for t in data["terms"]}
    existing_de = {normalize_de(t["de"]) for t in data["terms"]}
    existing_base = {normalize_de(t.get("de_base", t["de"])) for t in data["terms"]}

    added = 0
    skipped = 0

    for term in NEW_TERMS:
        tid = term["id"]
        de_key = normalize_de(term["de"])
        base_key = normalize_de(term.get("de_base", term["de"]))

        if tid in existing_ids:
            skipped += 1
            continue
        if de_key in existing_de or base_key in existing_base:
            skipped += 1
            continue

        entry = dict(term)
        entry.setdefault("tags", [])
        data["terms"].append(entry)
        existing_ids.add(tid)
        existing_de.add(de_key)
        existing_base.add(base_key)
        added += 1

    data["meta"]["term_count"] = len(data["terms"])

    with open(VOCAB_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Added {added} terms ({skipped} skipped as duplicates)")
    print(f"term_count → {data['meta']['term_count']}")


if __name__ == "__main__":
    main()
